<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pet;
use App\Models\Category;
use App\Models\Shelter;

class PetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();
        $shelters = Shelter::all();

        if ($categories->isEmpty() || $shelters->isEmpty()) {
            $this->command->error('Please run CategorySeeder and ShelterSeeder first!');
            return;
        }

        $dogCategory = $categories->where('slug', 'anjing')->first();
        $catCategory = $categories->where('slug', 'kucing')->first();
        $rabbitCategory = $categories->where('slug', 'kelinci')->first();

        $pets = [
            // Anjing
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $dogCategory->id,
                'name' => 'Max',
                'gender' => 'male',
                'age_years' => 2,
                'age_months' => 3,
                'breed' => 'Golden Retriever',
                'size' => 'large',
                'color' => 'Golden',
                'weight' => 30.5,
                'description' => 'Max adalah anjing yang sangat ramah dan suka bermain. Dia sangat cocok untuk keluarga dengan anak-anak.',
                'health_info' => 'Sehat, sudah divaksin lengkap',
                'personality' => 'Ramah, aktif, suka bermain',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => true,
                'good_with_cats' => false,
                'primary_image' => '/images/pets/max.jpg',
                'status' => 'available',
                'is_featured' => true,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $dogCategory->id,
                'name' => 'Buddy',
                'gender' => 'male',
                'age_years' => 1,
                'age_months' => 6,
                'breed' => 'Labrador',
                'size' => 'large',
                'color' => 'Coklat',
                'weight' => 28.0,
                'description' => 'Buddy adalah anjing muda yang energik dan suka belajar trik baru.',
                'health_info' => 'Sehat, vaksin lengkap',
                'personality' => 'Energik, pintar, mudah dilatih',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => true,
                'good_with_cats' => true,
                'primary_image' => '/images/pets/buddy.jpg',
                'status' => 'available',
                'is_featured' => true,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $dogCategory->id,
                'name' => 'Luna',
                'gender' => 'female',
                'age_years' => 3,
                'age_months' => 0,
                'breed' => 'Beagle',
                'size' => 'medium',
                'color' => 'Tricolor',
                'weight' => 12.5,
                'description' => 'Luna adalah anjing yang tenang dan penyayang. Cocok untuk pemilik pertama kali.',
                'health_info' => 'Sehat, steril',
                'personality' => 'Tenang, penyayang, loyal',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => true,
                'good_with_cats' => true,
                'primary_image' => '/images/pets/luna.jpg',
                'status' => 'available',
                'is_featured' => false,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $dogCategory->id,
                'name' => 'Rocky',
                'gender' => 'male',
                'age_years' => 4,
                'age_months' => 2,
                'breed' => 'German Shepherd',
                'size' => 'large',
                'color' => 'Hitam dan Tan',
                'weight' => 35.0,
                'description' => 'Rocky adalah anjing penjaga yang setia dan protektif terhadap keluarganya.',
                'health_info' => 'Sehat, vaksin lengkap',
                'personality' => 'Setia, protektif, pintar',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => false,
                'good_with_cats' => false,
                'primary_image' => '/images/pets/rocky.jpg',
                'status' => 'available',
                'is_featured' => true,
            ],
            // Kucing
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $catCategory->id,
                'name' => 'Whiskers',
                'gender' => 'male',
                'age_years' => 1,
                'age_months' => 0,
                'breed' => 'Persian',
                'size' => 'medium',
                'color' => 'Putih',
                'weight' => 4.5,
                'description' => 'Whiskers adalah kucing persia yang cantik dengan bulu putih halus.',
                'health_info' => 'Sehat, vaksin lengkap',
                'personality' => 'Tenang, manis, suka dipeluk',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => false,
                'good_with_cats' => true,
                'primary_image' => '/images/pets/whiskers.jpg',
                'status' => 'available',
                'is_featured' => true,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $catCategory->id,
                'name' => 'Milo',
                'gender' => 'male',
                'age_years' => 0,
                'age_months' => 6,
                'breed' => 'Domestic Shorthair',
                'size' => 'small',
                'color' => 'Oren',
                'weight' => 2.8,
                'description' => 'Milo adalah anak kucing yang playful dan menggemaskan.',
                'health_info' => 'Sehat, vaksin dasar',
                'personality' => 'Playful, energik, penasaran',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => true,
                'good_with_cats' => true,
                'primary_image' => '/images/pets/milo.jpg',
                'status' => 'available',
                'is_featured' => true,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $catCategory->id,
                'name' => 'Bella',
                'gender' => 'female',
                'age_years' => 2,
                'age_months' => 0,
                'breed' => 'Maine Coon',
                'size' => 'large',
                'color' => 'Tabby',
                'weight' => 6.0,
                'description' => 'Bella adalah kucing besar yang lembut dan penyayang.',
                'health_info' => 'Sehat, steril, vaksin lengkap',
                'personality' => 'Lembut, penyayang, tenang',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => true,
                'good_with_cats' => true,
                'primary_image' => '/images/pets/bella.jpg',
                'status' => 'available',
                'is_featured' => false,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $catCategory->id,
                'name' => 'Shadow',
                'gender' => 'male',
                'age_years' => 3,
                'age_months' => 6,
                'breed' => 'British Shorthair',
                'size' => 'medium',
                'color' => 'Abu-abu',
                'weight' => 5.2,
                'description' => 'Shadow adalah kucing yang mandiri namun tetap affectionate.',
                'health_info' => 'Sehat, vaksin lengkap',
                'personality' => 'Mandiri, tenang, loyal',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => false,
                'good_with_cats' => true,
                'primary_image' => '/images/pets/shadow.jpg',
                'status' => 'available',
                'is_featured' => true,
            ],
            // Kelinci
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $rabbitCategory->id,
                'name' => 'Fluffy',
                'gender' => 'female',
                'age_years' => 1,
                'age_months' => 3,
                'breed' => 'Holland Lop',
                'size' => 'small',
                'color' => 'Coklat Putih',
                'weight' => 1.5,
                'description' => 'Fluffy adalah kelinci mini yang sangat menggemaskan dengan telinga lop yang lucu.',
                'health_info' => 'Sehat, vaksin lengkap',
                'personality' => 'Ramah, tenang, suka dipeluk',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_house_trained' => true,
                'good_with_kids' => true,
                'good_with_dogs' => false,
                'good_with_cats' => false,
                'primary_image' => '/images/pets/fluffy.jpg',
                'status' => 'available',
                'is_featured' => false,
            ],
            [
                'shelter_id' => $shelters->random()->id,
                'category_id' => $rabbitCategory->id,
                'name' => 'Snowball',
                'gender' => 'male',
                'age_years' => 0,
                'age_months' => 8,
                'breed' => 'Lionhead',
                'size' => 'small',
                'color' => 'Putih',
                'weight' => 1.2,
                'description' => 'Snowball adalah kelinci putih dengan bulu yang halus seperti kapas.',
                'health_info' => 'Sehat',
                'personality' => 'Aktif, penasaran, playful',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_house_trained' => false,
                'good_with_kids' => true,
                'good_with_dogs' => false,
                'good_with_cats' => false,
                'primary_image' => '/images/pets/snowball.jpg',
                'status' => 'available',
                'is_featured' => false,
            ],
        ];

        foreach ($pets as $pet) {
            Pet::create($pet);
        }
    }
}
